//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGameClient.UserManagementReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Model.Model")]
    [System.SerializableAttribute()]
    public partial class CGUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGameClient.UserManagementReference.CGUser.UserStatus userStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGameClient.UserManagementReference.CGUser.UserType userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGameClient.UserManagementReference.CGUser.UserStatus userStatus {
            get {
                return this.userStatusField;
            }
            set {
                if ((this.userStatusField.Equals(value) != true)) {
                    this.userStatusField = value;
                    this.RaisePropertyChanged("userStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGameClient.UserManagementReference.CGUser.UserType userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CGUser.UserStatus", Namespace="http://schemas.datacontract.org/2004/07/Server.Model.Model")]
        public enum UserStatus : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UNATTACKABLE = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ATTACKABLE = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            STUNNED = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INGAME = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CGUser.UserType", Namespace="http://schemas.datacontract.org/2004/07/Server.Model.Model")]
        public enum UserType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PLAYER = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ADMIN = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementReference.IUserManagementService")]
    public interface IUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/CreateUser", ReplyAction="http://tempuri.org/IUserManagementService/CreateUserResponse")]
        void CreateUser(string id, string email, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/CreateUser", ReplyAction="http://tempuri.org/IUserManagementService/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string id, string email, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetUserByUserId", ReplyAction="http://tempuri.org/IUserManagementService/GetUserByUserIdResponse")]
        WebGameClient.UserManagementReference.CGUser GetUserByUserId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetUserByUserId", ReplyAction="http://tempuri.org/IUserManagementService/GetUserByUserIdResponse")]
        System.Threading.Tasks.Task<WebGameClient.UserManagementReference.CGUser> GetUserByUserIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/UpdateUser", ReplyAction="http://tempuri.org/IUserManagementService/UpdateUserResponse")]
        void UpdateUser(WebGameClient.UserManagementReference.CGUser cguser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/UpdateUser", ReplyAction="http://tempuri.org/IUserManagementService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(WebGameClient.UserManagementReference.CGUser cguser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementServiceChannel : WebGameClient.UserManagementReference.IUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceClient : System.ServiceModel.ClientBase<WebGameClient.UserManagementReference.IUserManagementService>, WebGameClient.UserManagementReference.IUserManagementService {
        
        public UserManagementServiceClient() {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string id, string email, string userName) {
            base.Channel.CreateUser(id, email, userName);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string id, string email, string userName) {
            return base.Channel.CreateUserAsync(id, email, userName);
        }
        
        public WebGameClient.UserManagementReference.CGUser GetUserByUserId(string id) {
            return base.Channel.GetUserByUserId(id);
        }
        
        public System.Threading.Tasks.Task<WebGameClient.UserManagementReference.CGUser> GetUserByUserIdAsync(string id) {
            return base.Channel.GetUserByUserIdAsync(id);
        }
        
        public void UpdateUser(WebGameClient.UserManagementReference.CGUser cguser) {
            base.Channel.UpdateUser(cguser);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(WebGameClient.UserManagementReference.CGUser cguser) {
            return base.Channel.UpdateUserAsync(cguser);
        }
    }
}
