//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopGameClient.GameTableServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGUser", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CGUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.Card[] cardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.CGUser.UserStatus userStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.CGUser.UserType userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.Card[] cards {
            get {
                return this.cardsField;
            }
            set {
                if ((object.ReferenceEquals(this.cardsField, value) != true)) {
                    this.cardsField = value;
                    this.RaisePropertyChanged("cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.CGUser.UserStatus userStatus {
            get {
                return this.userStatusField;
            }
            set {
                if ((this.userStatusField.Equals(value) != true)) {
                    this.userStatusField = value;
                    this.RaisePropertyChanged("userStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.CGUser.UserType userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CGUser.UserStatus", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
        public enum UserStatus : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UNATTACKABLE = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ATTACKABLE = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            STUNNED = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INGAME = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CGUser.UserType", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
        public enum UserType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PLAYER = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ADMIN = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.Card.CardType cardtypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.Card.CardType cardtype {
            get {
                return this.cardtypeField;
            }
            set {
                if ((this.cardtypeField.Equals(value) != true)) {
                    this.cardtypeField = value;
                    this.RaisePropertyChanged("cardtype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Card.CardType", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
        public enum CardType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ATTACK = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DEFENSE = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            EFFECT = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameTable", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.Deck DeckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.CGUser[] UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.Deck Deck {
            get {
                return this.DeckField;
            }
            set {
                if ((object.ReferenceEquals(this.DeckField, value) != true)) {
                    this.DeckField = value;
                    this.RaisePropertyChanged("Deck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.CGUser[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seats {
            get {
                return this.seatsField;
            }
            set {
                if ((this.seatsField.Equals(value) != true)) {
                    this.seatsField = value;
                    this.RaisePropertyChanged("seats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deck", Namespace="http://schemas.datacontract.org/2004/07/Server.DataContracts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Deck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeckNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DesktopGameClient.GameTableServiceReference.Card[] cardsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeckName {
            get {
                return this.DeckNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeckNameField, value) != true)) {
                    this.DeckNameField = value;
                    this.RaisePropertyChanged("DeckName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DesktopGameClient.GameTableServiceReference.Card[] cards {
            get {
                return this.cardsField;
            }
            set {
                if ((object.ReferenceEquals(this.cardsField, value) != true)) {
                    this.cardsField = value;
                    this.RaisePropertyChanged("cards");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameTableServiceReference.IGameTableManagementService")]
    public interface IGameTableManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/CreateGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/CreateGameTableResponse")]
        DesktopGameClient.GameTableServiceReference.GameTable CreateGameTable(DesktopGameClient.GameTableServiceReference.CGUser user, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/CreateGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/CreateGameTableResponse")]
        System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> CreateGameTableAsync(DesktopGameClient.GameTableServiceReference.CGUser user, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/DeleteGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/DeleteGameTableResponse")]
        bool DeleteGameTable(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/DeleteGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/DeleteGameTableResponse")]
        System.Threading.Tasks.Task<bool> DeleteGameTableAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetGameTableById", ReplyAction="http://tempuri.org/IGameTableManagementService/GetGameTableByIdResponse")]
        DesktopGameClient.GameTableServiceReference.GameTable GetGameTableById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetGameTableById", ReplyAction="http://tempuri.org/IGameTableManagementService/GetGameTableByIdResponse")]
        System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> GetGameTableByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetAll", ReplyAction="http://tempuri.org/IGameTableManagementService/GetAllResponse")]
        DesktopGameClient.GameTableServiceReference.GameTable[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetAll", ReplyAction="http://tempuri.org/IGameTableManagementService/GetAllResponse")]
        System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetGameTableByTableName", ReplyAction="http://tempuri.org/IGameTableManagementService/GetGameTableByTableNameResponse")]
        DesktopGameClient.GameTableServiceReference.GameTable GetGameTableByTableName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/GetGameTableByTableName", ReplyAction="http://tempuri.org/IGameTableManagementService/GetGameTableByTableNameResponse")]
        System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> GetGameTableByTableNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/JoinGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/JoinGameTableResponse")]
        DesktopGameClient.GameTableServiceReference.GameTable JoinGameTable(DesktopGameClient.GameTableServiceReference.CGUser user, DesktopGameClient.GameTableServiceReference.GameTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/JoinGameTable", ReplyAction="http://tempuri.org/IGameTableManagementService/JoinGameTableResponse")]
        System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> JoinGameTableAsync(DesktopGameClient.GameTableServiceReference.CGUser user, DesktopGameClient.GameTableServiceReference.GameTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/UpdateGameTableSeats", ReplyAction="http://tempuri.org/IGameTableManagementService/UpdateGameTableSeatsResponse")]
        void UpdateGameTableSeats(DesktopGameClient.GameTableServiceReference.GameTable gameTable, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameTableManagementService/UpdateGameTableSeats", ReplyAction="http://tempuri.org/IGameTableManagementService/UpdateGameTableSeatsResponse")]
        System.Threading.Tasks.Task UpdateGameTableSeatsAsync(DesktopGameClient.GameTableServiceReference.GameTable gameTable, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameTableManagementServiceChannel : DesktopGameClient.GameTableServiceReference.IGameTableManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameTableManagementServiceClient : System.ServiceModel.ClientBase<DesktopGameClient.GameTableServiceReference.IGameTableManagementService>, DesktopGameClient.GameTableServiceReference.IGameTableManagementService {
        
        public GameTableManagementServiceClient() {
        }
        
        public GameTableManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameTableManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameTableManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameTableManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DesktopGameClient.GameTableServiceReference.GameTable CreateGameTable(DesktopGameClient.GameTableServiceReference.CGUser user, string tableName) {
            return base.Channel.CreateGameTable(user, tableName);
        }
        
        public System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> CreateGameTableAsync(DesktopGameClient.GameTableServiceReference.CGUser user, string tableName) {
            return base.Channel.CreateGameTableAsync(user, tableName);
        }
        
        public bool DeleteGameTable(int id) {
            return base.Channel.DeleteGameTable(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteGameTableAsync(int id) {
            return base.Channel.DeleteGameTableAsync(id);
        }
        
        public DesktopGameClient.GameTableServiceReference.GameTable GetGameTableById(int id) {
            return base.Channel.GetGameTableById(id);
        }
        
        public System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> GetGameTableByIdAsync(int id) {
            return base.Channel.GetGameTableByIdAsync(id);
        }
        
        public DesktopGameClient.GameTableServiceReference.GameTable[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public DesktopGameClient.GameTableServiceReference.GameTable GetGameTableByTableName(string name) {
            return base.Channel.GetGameTableByTableName(name);
        }
        
        public System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> GetGameTableByTableNameAsync(string name) {
            return base.Channel.GetGameTableByTableNameAsync(name);
        }
        
        public DesktopGameClient.GameTableServiceReference.GameTable JoinGameTable(DesktopGameClient.GameTableServiceReference.CGUser user, DesktopGameClient.GameTableServiceReference.GameTable table) {
            return base.Channel.JoinGameTable(user, table);
        }
        
        public System.Threading.Tasks.Task<DesktopGameClient.GameTableServiceReference.GameTable> JoinGameTableAsync(DesktopGameClient.GameTableServiceReference.CGUser user, DesktopGameClient.GameTableServiceReference.GameTable table) {
            return base.Channel.JoinGameTableAsync(user, table);
        }
        
        public void UpdateGameTableSeats(DesktopGameClient.GameTableServiceReference.GameTable gameTable, int amount) {
            base.Channel.UpdateGameTableSeats(gameTable, amount);
        }
        
        public System.Threading.Tasks.Task UpdateGameTableSeatsAsync(DesktopGameClient.GameTableServiceReference.GameTable gameTable, int amount) {
            return base.Channel.UpdateGameTableSeatsAsync(gameTable, amount);
        }
    }
}
